on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    #- name: esp-idf build
    #  uses: espressif/esp-idf-ci-action@v1
    #  with:
    #    esp_idf_version: v4.4
    #    target: esp32s2
    #    path: 'st-device-sdk-c-ref/apps/esp32/switch_example'

    - name: Setup
      run:  python setup.py esp32
    - name: Clean
      run:  python build.py esp32 switch_example clean
    - name: Build
      run:  python build.py esp32 switch_example
