on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup for esp32
      run:  ./setup.sh esp32
    - name: Build switch_example
      run:  ./build.sh esp32 switch_example

    - name: Upload switch_example
      uses: actions/upload-artifact@v4
      with:
        name: switch_example.bin 
        path: |
          build/switch_example.bin

    - name: Upload binaries to release
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: switch_example.bin
        asset_name: kerpz_$tag.bin
        tag: ${{ github.ref }}
        overwrite: true
        release_name: release ${{ github.ref_name }}     
   
